# Form implementation generated from reading ui file 'ExitWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ExitWindow(object):
    def setupUi(self, ExitWindow):
        ExitWindow.setObjectName("ExitWindow")
        ExitWindow.resize(400, 200)
        ExitWindow.setMinimumSize(QtCore.QSize(400, 200))
        ExitWindow.setMaximumSize(QtCore.QSize(400, 200))
        self.lblSalir = QtWidgets.QLabel(parent=ExitWindow)
        self.lblSalir.setGeometry(QtCore.QRect(80, 50, 250, 50))
        self.lblSalir.setMinimumSize(QtCore.QSize(250, 50))
        self.lblSalir.setMaximumSize(QtCore.QSize(250, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblSalir.setFont(font)
        self.lblSalir.setObjectName("lblSalir")
        self.btnOk = QtWidgets.QPushButton(parent=ExitWindow)
        self.btnOk.setGeometry(QtCore.QRect(50, 150, 100, 30))
        self.btnOk.setMinimumSize(QtCore.QSize(100, 30))
        self.btnOk.setMaximumSize(QtCore.QSize(100, 30))
        self.btnOk.setObjectName("btnOk")
        self.btnCancel = QtWidgets.QPushButton(parent=ExitWindow)
        self.btnCancel.setGeometry(QtCore.QRect(250, 150, 100, 30))
        self.btnCancel.setMinimumSize(QtCore.QSize(100, 30))
        self.btnCancel.setMaximumSize(QtCore.QSize(100, 30))
        self.btnCancel.setObjectName("btnCancel")

        self.retranslateUi(ExitWindow)
        QtCore.QMetaObject.connectSlotsByName(ExitWindow)

    def retranslateUi(self, ExitWindow):
        _translate = QtCore.QCoreApplication.translate
        ExitWindow.setWindowTitle(_translate("ExitWindow", "Form"))
        self.lblSalir.setText(_translate("ExitWindow", "¿Salir de la aplicacion?"))
        self.btnOk.setText(_translate("ExitWindow", "Ok"))
        self.btnCancel.setText(_translate("ExitWindow", "Cancel"))
