# Form implementation generated from reading ui file 'acercade.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAcercaDe(object):
    def setupUi(self, dlgAcercaDe):
        dlgAcercaDe.setObjectName("dlgAcercaDe")
        dlgAcercaDe.resize(399, 302)
        self.frame = QtWidgets.QFrame(parent=dlgAcercaDe)
        self.frame.setGeometry(QtCore.QRect(30, 20, 341, 191))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.lbl1 = QtWidgets.QLabel(parent=self.frame)
        self.lbl1.setGeometry(QtCore.QRect(160, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl1.setFont(font)
        self.lbl1.setObjectName("lbl1")
        self.lbl2 = QtWidgets.QLabel(parent=self.frame)
        self.lbl2.setGeometry(QtCore.QRect(160, 50, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl2.setFont(font)
        self.lbl2.setObjectName("lbl2")
        self.lbl3 = QtWidgets.QLabel(parent=self.frame)
        self.lbl3.setGeometry(QtCore.QRect(160, 80, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl3.setFont(font)
        self.lbl3.setObjectName("lbl3")
        self.lbl4 = QtWidgets.QLabel(parent=self.frame)
        self.lbl4.setGeometry(QtCore.QRect(180, 170, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl4.setFont(font)
        self.lbl4.setObjectName("lbl4")
        self.lbl5 = QtWidgets.QLabel(parent=self.frame)
        self.lbl5.setGeometry(QtCore.QRect(250, 140, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl5.setFont(font)
        self.lbl5.setObjectName("lbl5")
        self.btnCerrarAbout = QtWidgets.QPushButton(parent=dlgAcercaDe)
        self.btnCerrarAbout.setGeometry(QtCore.QRect(150, 240, 75, 23))
        self.btnCerrarAbout.setObjectName("btnCerrarAbout")

        self.retranslateUi(dlgAcercaDe)
        QtCore.QMetaObject.connectSlotsByName(dlgAcercaDe)

    def retranslateUi(self, dlgAcercaDe):
        _translate = QtCore.QCoreApplication.translate
        dlgAcercaDe.setWindowTitle(_translate("dlgAcercaDe", "Dialog"))
        self.lbl1.setText(_translate("dlgAcercaDe", "Car Teis"))
        self.lbl2.setText(_translate("dlgAcercaDe", "Alquiler de Coches"))
        self.lbl3.setText(_translate("dlgAcercaDe", "Version 0.0.1"))
        self.lbl4.setText(_translate("dlgAcercaDe", "Diego Ribas Gonzalez"))
        self.lbl5.setText(_translate("dlgAcercaDe", "IES de Teis"))
        self.btnCerrarAbout.setText(_translate("dlgAcercaDe", "Cerrar"))
