# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WindowMain(object):
    def setupUi(self, WindowMain):
        WindowMain.setObjectName("WindowMain")
        WindowMain.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(WindowMain.sizePolicy().hasHeightForWidth())
        WindowMain.setSizePolicy(sizePolicy)
        WindowMain.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(parent=WindowMain)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSalir = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSalir.setGeometry(QtCore.QRect(330, 240, 120, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSalir.sizePolicy().hasHeightForWidth())
        self.btnSalir.setSizePolicy(sizePolicy)
        self.btnSalir.setMinimumSize(QtCore.QSize(120, 20))
        self.btnSalir.setMaximumSize(QtCore.QSize(120, 20))
        self.btnSalir.setObjectName("btnSalir")
        self.lblTitulo = QtWidgets.QLabel(parent=self.centralwidget)
        self.lblTitulo.setGeometry(QtCore.QRect(340, 150, 120, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblTitulo.sizePolicy().hasHeightForWidth())
        self.lblTitulo.setSizePolicy(sizePolicy)
        self.lblTitulo.setMinimumSize(QtCore.QSize(120, 20))
        self.lblTitulo.setMaximumSize(QtCore.QSize(240, 40))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTitulo.setFont(font)
        self.lblTitulo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblTitulo.setObjectName("lblTitulo")
        WindowMain.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=WindowMain)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(parent=self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAyuda = QtWidgets.QMenu(parent=self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        WindowMain.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=WindowMain)
        self.statusbar.setObjectName("statusbar")
        WindowMain.setStatusBar(self.statusbar)
        self.actionAcerca_de = QtGui.QAction(parent=WindowMain)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.actionSalir = QtGui.QAction(parent=WindowMain)
        self.actionSalir.setObjectName("actionSalir")
        self.menuArchivo.addAction(self.actionSalir)
        self.menuAyuda.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(WindowMain)
        QtCore.QMetaObject.connectSlotsByName(WindowMain)

    def retranslateUi(self, WindowMain):
        _translate = QtCore.QCoreApplication.translate
        WindowMain.setWindowTitle(_translate("WindowMain", "CarTeis"))
        self.btnSalir.setText(_translate("WindowMain", "Salir"))
        self.lblTitulo.setText(_translate("WindowMain", "Car Teis"))
        self.menuArchivo.setTitle(_translate("WindowMain", "Archivo"))
        self.menuAyuda.setTitle(_translate("WindowMain", "Ayuda"))
        self.actionAcerca_de.setText(_translate("WindowMain", "Acerca de"))
        self.actionSalir.setText(_translate("WindowMain", "Salir"))
