# Form implementation generated from reading ui file 'salir.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgSalir(object):
    def setupUi(self, dlgSalir):
        dlgSalir.setObjectName("dlgSalir")
        dlgSalir.resize(400, 300)
        self.lblSalir = QtWidgets.QLabel(parent=dlgSalir)
        self.lblSalir.setGeometry(QtCore.QRect(80, 90, 241, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lblSalir.setFont(font)
        self.lblSalir.setObjectName("lblSalir")
        self.btnSalirAceptar = QtWidgets.QPushButton(parent=dlgSalir)
        self.btnSalirAceptar.setGeometry(QtCore.QRect(60, 210, 75, 23))
        self.btnSalirAceptar.setObjectName("btnSalirAceptar")
        self.btnSalirCancelar = QtWidgets.QPushButton(parent=dlgSalir)
        self.btnSalirCancelar.setGeometry(QtCore.QRect(250, 210, 75, 23))
        self.btnSalirCancelar.setObjectName("btnSalirCancelar")

        self.retranslateUi(dlgSalir)
        QtCore.QMetaObject.connectSlotsByName(dlgSalir)

    def retranslateUi(self, dlgSalir):
        _translate = QtCore.QCoreApplication.translate
        dlgSalir.setWindowTitle(_translate("dlgSalir", "Dialog"))
        self.lblSalir.setText(_translate("dlgSalir", "¿DESEA USTED SALIR?"))
        self.btnSalirAceptar.setText(_translate("dlgSalir", "Aceptar"))
        self.btnSalirCancelar.setText(_translate("dlgSalir", "Cancelar"))
